//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferencePostComment
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostDTO", Namespace="http://schemas.datacontract.org/2004/07/PostComment")]
    public partial class PostDTO : object
    {
        
        private System.Collections.Generic.List<ServiceReferencePostComment.CommentDTO> CommentsField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string DomainField;
        
        private int PostIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferencePostComment.CommentDTO> Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId
        {
            get
            {
                return this.PostIdField;
            }
            set
            {
                this.PostIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentDTO", Namespace="http://schemas.datacontract.org/2004/07/PostComment", IsReference=true)]
    public partial class CommentDTO : object
    {
        
        private int CommentIdField;
        
        private ServiceReferencePostComment.PostDTO PostField;
        
        private int PostPostIdField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId
        {
            get
            {
                return this.CommentIdField;
            }
            set
            {
                this.CommentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferencePostComment.PostDTO Post
        {
            get
            {
                return this.PostField;
            }
            set
            {
                this.PostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostPostId
        {
            get
            {
                return this.PostPostIdField;
            }
            set
            {
                this.PostPostIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePostComment.IPostComment")]
    public interface IPostComment
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/Cleanup", ReplyAction="http://tempuri.org/IPost/CleanupResponse")]
        System.Threading.Tasks.Task CleanupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetPostById", ReplyAction="http://tempuri.org/IPost/GetPostByIdResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> GetPostByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetPostByTitle", ReplyAction="http://tempuri.org/IPost/GetPostByTitleResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> GetPostByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/SubmitPost", ReplyAction="http://tempuri.org/IPost/SubmitPostResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> SubmitPostAsync(ServiceReferencePostComment.PostDTO post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/UpdatePost", ReplyAction="http://tempuri.org/IPost/UpdatePostResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> UpdatePostAsync(ServiceReferencePostComment.PostDTO newPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/DeletePost", ReplyAction="http://tempuri.org/IPost/DeletePostResponse")]
        System.Threading.Tasks.Task<int> DeletePostAsync(int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPost/GetAllPosts", ReplyAction="http://tempuri.org/IPost/GetAllPostsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePostComment.PostDTO>> GetAllPostsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/GetCommentById", ReplyAction="http://tempuri.org/IComment/GetCommentByIdResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> GetCommentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/SubmitComment", ReplyAction="http://tempuri.org/IComment/SubmitCommentResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> SubmitCommentAsync(ServiceReferencePostComment.CommentDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/AddCommment", ReplyAction="http://tempuri.org/IComment/AddCommmentResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> AddCommmentAsync(int postId, ServiceReferencePostComment.CommentDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/UpdateComment", ReplyAction="http://tempuri.org/IComment/UpdateCommentResponse")]
        System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> UpdateCommentAsync(ServiceReferencePostComment.CommentDTO oldComment, ServiceReferencePostComment.CommentDTO newComment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComment/DeleteComment", ReplyAction="http://tempuri.org/IComment/DeleteCommentResponse")]
        System.Threading.Tasks.Task<bool> DeleteCommentAsync(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoadData/GetAllPostsAndRelatedComments", ReplyAction="http://tempuri.org/ILoadData/GetAllPostsAndRelatedCommentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePostComment.PostDTO>> GetAllPostsAndRelatedCommentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPostCommentChannel : ServiceReferencePostComment.IPostComment, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PostCommentClient : System.ServiceModel.ClientBase<ServiceReferencePostComment.IPostComment>, ServiceReferencePostComment.IPostComment
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PostCommentClient() : 
                base(PostCommentClient.GetDefaultBinding(), PostCommentClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPostComment.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostCommentClient(EndpointConfiguration endpointConfiguration) : 
                base(PostCommentClient.GetBindingForEndpoint(endpointConfiguration), PostCommentClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostCommentClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PostCommentClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostCommentClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PostCommentClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PostCommentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task CleanupAsync()
        {
            return base.Channel.CleanupAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> GetPostByIdAsync(int id)
        {
            return base.Channel.GetPostByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> GetPostByTitleAsync(string title)
        {
            return base.Channel.GetPostByTitleAsync(title);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> SubmitPostAsync(ServiceReferencePostComment.PostDTO post)
        {
            return base.Channel.SubmitPostAsync(post);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.PostDTO> UpdatePostAsync(ServiceReferencePostComment.PostDTO newPost)
        {
            return base.Channel.UpdatePostAsync(newPost);
        }
        
        public System.Threading.Tasks.Task<int> DeletePostAsync(int postId)
        {
            return base.Channel.DeletePostAsync(postId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePostComment.PostDTO>> GetAllPostsAsync()
        {
            return base.Channel.GetAllPostsAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> GetCommentByIdAsync(int id)
        {
            return base.Channel.GetCommentByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> SubmitCommentAsync(ServiceReferencePostComment.CommentDTO comment)
        {
            return base.Channel.SubmitCommentAsync(comment);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> AddCommmentAsync(int postId, ServiceReferencePostComment.CommentDTO comment)
        {
            return base.Channel.AddCommmentAsync(postId, comment);
        }
        
        public System.Threading.Tasks.Task<ServiceReferencePostComment.CommentDTO> UpdateCommentAsync(ServiceReferencePostComment.CommentDTO oldComment, ServiceReferencePostComment.CommentDTO newComment)
        {
            return base.Channel.UpdateCommentAsync(oldComment, newComment);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCommentAsync(int commentId)
        {
            return base.Channel.DeleteCommentAsync(commentId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReferencePostComment.PostDTO>> GetAllPostsAndRelatedCommentsAsync()
        {
            return base.Channel.GetAllPostsAndRelatedCommentsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPostComment))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPostComment))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PostCommentClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPostComment);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PostCommentClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPostComment);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPostComment,
        }
    }
}
